
version: '2'

networks:
  terms:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.67.0/24
        gateway: 172.19.67.1

services:

  postgresql:
    build: dockerfiles/postgresql/
    image: enriquepablo/postgresql:0.1
    hostname: postgresql
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
      - ./log/postgresql:/var/log/postgresql
    networks:
      terms:
        ipv4_address: 172.19.67.100

  terms:
    build: dockerfiles/terms/
    image: enriquepablo/terms:0.1
    hostname: terms
    ports:
      - "1967:1967"
    expose:
      - 1967
    links:
      - postgresql
    volumes:
      - ./log/terms:/opt/terms-project/var/log
      - ./etc/terms:/opt/terms-project/etc
    networks:
      terms:
        ipv4_address: 172.19.67.101
    depends_on:
      - postgresql

  webserver:
    build: dockerfiles/terms.server/
    image: enriquepablo/terms-webserver:0.1
    hostname: webserver
    ports:
      - "8080:8080"
    expose:
      - 8080
    links:
      - postgresql
      - terms
    volumes:
      - ./log/webserver:/opt/tserve-buildout/var/log
      - ./etc/webserver:/opt/tserve-buildout/etc
    networks:
      terms:
        ipv4_address: 172.19.67.102
    depends_on:
      - postgresql
      - terms

  nginx:
    build: dockerfiles/nginx/
    image: enriquepablo/nginx:0.1
    hostname: eperez-ws.emergya.com
    links:
      - webserver
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx
    networks:
      terms:
        ipv4_address: 172.19.67.103
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=eperez-ws.emergya.com
      - NGINX_PORT=80
    command: ["/wait-for-it.sh", "webserver:8080", "-s", "-t", "3600", "--", "nginx"]
    depends_on:
      - webserver
