version: '2'

volumes:
  logs_pg: {}
  data_pg: {}
  logs_ts: {}

services:
  notebook:
    image: enriquepablo/terms-notebook:0.2
    hostname: notebook
    links:
      - termsserver
    environment:
      - KB_HOST=termsserver
      - KB_PORT=1967

    ports:
        - "8888:8888"

  termsserver:
    image: enriquepablo/terms-server:0.3
    hostname: termsserver
    links:
      - postgresql
    expose:
      - "1967"
    volumes:
      - logs_ts:/opt/terms-project/var/log

  postgresql:
    image: postgres:9.5
    hostname: postgresql
    environment:
      - POSTGRES_USER=terms
      - POSTGRES_PASSWORD=terms
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    volumes:
      - data_pg:/var/lib/postgresql/data/pgdata
      - logs_pg:/var/log/postgresql
