
notebook:
  image: enriquepablo/terms-notebook:0.1
  hostname: notebook
  links:
    - termsserver
  environment:
    - KB_HOST=172.17.0.3
    - KB_PORT=1967
  ports:
      - "8888:8888"

termsserver:
  image: enriquepablo/terms-server:0.1
  hostname: termsserver
  links:
    - postgresql
  expose:
    - "1967"
  volumes:
    - logs:/opt/terms-project/var/log

postgresql:
  image: postgres:9.5
  environment:
    - POSTGRES_USER=terms
    - POSTGRES_PASSWORD=terms
    - PGDATA=/var/lib/postgresql/data/pgdata
  expose:
    - "5432"
  volumes:
    - data:/var/lib/postgresql/data/pgdata
    - logs:/var/log/postgresql
